# Generated by Django 5.0 on 2025-05-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilgrimageDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='نام مقصد زیارتی')),
            ],
            options={
                'verbose_name': 'مقصد',
                'verbose_name_plural': 'مقاصد زیارتی',
            },
        ),
    ]
