# Generated by Django 5.0 on 2025-05-31 07:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دسته بندی')),
                ('url_title', models.CharField(max_length=255, verbose_name='عنوان دسته بندی به انگلیسی')),
            ],
            options={
                'verbose_name': 'دسته بندی سوالات پرتکرار',
                'verbose_name_plural': 'دسته بندی های سوالات پرتکرار',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^((\\+98|0)9\\d{9})$', message='شماره تلفن صحیح نمیباشد')], verbose_name='شماره تلفن')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Gallery', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='SettingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='لوگو')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات های سایت',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='درباره ما')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_module.gallery', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='QustionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='عنوان سوال')),
                ('response', models.TextField(verbose_name='پاسخ سوال')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home_module.categoryfaq', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سوال و جواب',
                'verbose_name_plural': 'سوالات و پاسخ های سوالات پرتکرار',
            },
        ),
    ]
