# Generated by Django 5.0 on 2025-05-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_categoryfaq_contact_gallery_settingsite_aboutus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='images',
        ),
        migrations.AddField(
            model_name='gallery',
            name='show_in_aboutUs',
            field=models.BooleanField(default=True, verbose_name='در درباره ما نمایش داده شود؟'),
        ),
    ]
