# Generated by Django 5.0 on 2025-07-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_remove_aboutus_images_gallery_show_in_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست تماس', 'verbose_name_plural': 'درخواست های تماس'},
        ),
    ]
