# Generated by Django 5.0 on 2025-07-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0004_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsite',
            name='insurance_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین روز ثبت بیمه نامه'),
        ),
        migrations.AddField(
            model_name='settingsite',
            name='insurance_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='اولین روز ثبت بیمه نامه'),
        ),
    ]
