# Generated by Django 5.0 on 2025-07-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0005_settingsite_insurance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsite',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='آخرین روز ثبت بیمه نامه'),
        ),
        migrations.AlterField(
            model_name='settingsite',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='اولین روز ثبت بیمه نامه'),
        ),
    ]
