# Generated by Django 5.0 on 2025-07-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_module', '0003_alter_insurance_code_alter_insurance_origin_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاروان'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=6, verbose_name='کد رهگیری'),
        ),
    ]
