# Generated by Django 5.0 on 2025-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_module', '0004_insurance_insurance_name_alter_insurance_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=9, verbose_name='کد رهگیری'),
        ),
    ]
