# Generated by Django 5.0 on 2025-05-21 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(db_index=True, max_length=120, verbose_name='کدملی')),
                ('phone', models.CharField(max_length=120, unique=True, verbose_name='شماره تلفن')),
                ('is_active', models.BooleanField(default=False, verbose_name='حساب فعال / غیرفعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='حساب کاربر')),
                ('verify_code', models.CharField(blank=True, db_index=True, max_length=6, null=True, verbose_name='کد تایید')),
                ('expire_verify_code', models.DateTimeField(blank=True, null=True, verbose_name='انقضا کد تایید')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=30, verbose_name='کدملی')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to=settings.AUTH_USER_MODEL, verbose_name='سرگروه')),
            ],
            options={
                'verbose_name': 'زیر مجموعه',
                'verbose_name_plural': 'زیر مجموعه ها',
            },
        ),
    ]
