# Generated by Django 5.0 on 2025-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'زیر مجموعه', 'verbose_name_plural': 'زیر مجموعه ها'},
        ),
        migrations.AddField(
            model_name='subuser',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ ساخت'),
        ),
    ]
