# Generated by Django 5.0 on 2025-05-31 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_subuser_options_subuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^((\\+98|0)9\\d{9})$', message='شماره تلفن صحیح نمیباشد')], verbose_name='شماره تلفن'),
        ),
    ]
