# Generated by Django 5.0 on 2025-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False, null=True, verbose_name='تاریخ ساخت'),
        ),
    ]
