# Generated by Django 5.0 on 2025-07-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_subuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ ساخت'),
        ),
    ]
