# Generated by Django 5.0 on 2025-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_code', models.CharField(max_length=200, verbose_name='')),
                ('ref_id', models.CharField(max_length=250, verbose_name='')),
                ('pay_date', models.DateTimeField(verbose_name='')),
                ('price', models.CharField(max_length=250, verbose_name='')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش ها',
                'ordering': ['-pay_date'],
            },
        ),
    ]
