# Generated by Django 5.0 on 2025-07-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_module', '0003_alter_insurance_code_alter_insurance_origin_county_and_more'),
        ('payment_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='insurance_code',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='insurance',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='insurance_module.insurance', verbose_name='بیمه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='pay_date',
            field=models.DateTimeField(verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='price',
            field=models.CharField(max_length=250, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='ref_id',
            field=models.CharField(max_length=250, verbose_name='کد پرداخت'),
        ),
    ]
